### ISSUE TITLE
[DnD] Target node renderer

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-gse#60]
It is not really standard to change the text color to indicate which TreeNode is currently selected. For instance, in Windows Explorer, both source and target node are selected.

![screenshot](https://user-images.githubusercontent.com/17516110/46568525-9f29a380-c946-11e8-8522-2d23ea5beec2.PNG)

**Comment by nashousni** [comment]
so i should remove the color changes?

**Comment by nashousni** [comment]
the color changes while the TreeNode is overed not when it is selected

**Comment by mathbagu** [comment]
We have to visually indicate to the user the target node. You choose to do it by changing the color of the text, but I'm not sure it is the common way to do it (screenshot). If you choose a visual convention different of the standard conventions, our users could be lost.
Try to study how your preferred software highlight the target node, like I did with Windows Explorer and make proposal to improve this feature.
Examples:
- Window Explorer, Thunderbird: there is an opaque rectangle to identify the target node
- IntelliJ Idea: there is a transparent rectangle with red border (in dark skin) to identify the target node

**Comment by MioRtia** [comment]
Fixed #66
